In [1]:
import numpy as np
from models import K_Folds
from pmf import cross_validation,PMF

Not running from main.


In [2]:
train =[]
test = []
validate=[]
data_all =[]
for i in range(1, 6):
  data = np.loadtxt("data/u%d.base" % i)
  test = np.loadtxt("data/u%d.test" % i)
  train.append(data)
  validate.append(test)
  data_all.append(np.concatenate((data, test), axis=0))
num_user = 943
num_item = 1682

def g(x, w, random_seed=1):
  np.random.seed(random_seed)
  indexes = np.arange(5)
  w=int(w[0])
  indexes = np.delete(indexes, w)
  train_data = data_all[indexes[0]]
  indexes = np.delete(indexes, indexes[0])
  for i in indexes:
    train_data = np.concatenate((train_data, data_all[i]), axis=0)
  val = PMF(num_user, num_item, train_data, data_all[w], x[0], x[1], int(x[3]),
            int(x[2]))
  return -val * 100.0

In [3]:

log_mu = np.array([-1.43285632, -1.04592418, -27.03837878, -6.839643])

log_multi = np.array([5.09945529e+00,   3.14705582e-01 ,  2.76955350e+00 ,  2.59006831e+00,
       2.72541135e+00  ,-1.59429134e+01  ,-3.89236520e+00  , 2.81947210e+00,
      -1.41557863e+01 , -2.00693301e+01 ,  3.85411365e+00  , 2.46330959e+00,
      -1.79366753e+01 , -1.65765782e+01 , -1.79260710e+01])

mu = [1.72004110e+00, 1.01494883e+00 ,  5.52864499e+11 ,  9.34277539e+02]
num_dims = 5

# XWtrain = np.loadtxt("training_data/XWtrain_100_points.txt")
#yTrain = np.loadtxt("training_data/yTrain_100.txt")
#yTrain = yTrain.reshape((XWtrain.shape[0], 1))
#noise = np.loadtxt()
data = {}
#  data['X_data'] = XWtrain
# data['y'] = yTrain[:,0]
#data['noise'] = 1e-50*np.ones(len(yTrain[:,0]))
data['matern'] = mu
data['log_multiKernel'] = log_multi
data['nEvals'] = 2
data['dim_x'] = 4
data['dim_w'] = 1
data['evaluation_f'] = g

lower = [0.1, 0.01, 1, 1, 0]
upper = [51, 1.01, 21, 201, 5]

domain = []
for i in range(5):
  dict={}
  dict['lower'] = lower[i]
  dict['upper'] = upper[i]
  domain.append(dict)

data['domain'] = domain
data['type_domain'] = ['real', 'real', 'integer', 'integer', 'integer']
model = K_Folds(num_dims, **data)

In [5]:
model.test_plot()

/Users/saultoscano/anaconda/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [5]:
self=model

In [6]:
n=1

In [7]:
XW = self.objective_function.generate_random_points_in_domain(n)

In [8]:
XW

array([[  0.78793439,   0.54205787,  19.        ,  12.        ,   4.        ]])

In [9]:
 n_points = XW.shape[0]

In [10]:
self= self.objective_function

In [11]:
j=0

In [12]:
i=0

In [14]:
MAX_RANDOM_SEED = 1000000000

In [15]:
random_seeds = np.random.randint(1, MAX_RANDOM_SEED + 1, self.nEvals * n_points)

In [17]:
self.nEvals

2

In [16]:
random_seeds

array([ 90025416, 859580512])

In [18]:
samples = self.function(x=XW[j,0:self.dim_x], w=XW[j,self.dim_x:self.dim_x+self.dim_w],random_seed=random_seeds[j*self.nEvals + i])

In [22]:
XW = self.generate_random_points_in_domain(2)

In [23]:
XW

array([[  19.60922455,    0.24827961,   17.        ,  150.        ,    3.        ],
       [   3.95602395,    0.98455484,    2.        ,   60.        ,    2.        ]])

In [25]:
from joblib import(
    Parallel,
    delayed,
)


In [26]:
n_points = XW.shape[0]

random_seeds = np.random.randint(1, MAX_RANDOM_SEED + 1, self.nEvals * n_points)
samples = Parallel(n_jobs=self.nCores)(
    delayed(self.function)(
        x=XW[j,0:self.dim_x],
        w=XW[j,self.dim_x:self.dim_x+self.dim_w],
        random_seed=random_seeds[j*self.nEvals + i]
    ) for j in range(n_points) for i in range(self.nEvals)
)

In [27]:
samples

[-60.75448532518184,
 -60.71485561894503,
 -125.86963599870747,
 -125.92574264525513]

In [42]:
def f(*args):
    if args:
        args=args[0]
        print args

In [43]:
a=[2,3]

In [45]:
f(a)

[2, 3]


In [46]:
model

In [4]:
XWtrain = np.loadtxt("data/XWdata.txt")
yTrain = np.loadtxt("data/ydata.txt")

In [10]:
model._kernel.cross_cov( XWtrain,np.array([[  9.11933786e-01,   1.03580980e-01,   1.40000000e+01,
          1.62000000e+02,   4]]))

array([[ 7735.45001213],
       [ 6949.3496276 ],
       [ 1921.91541846],
       [ 5894.45694377],
       [  236.55623249],
       [  234.08458695],
       [  221.92910331],
       [   58.22204079],
       [  577.50492302],
       [  651.68446333],
       [  588.8182143 ],
       [  207.14091147],
       [  102.93695593],
       [   79.55583105],
       [   85.67929044],
       [   53.27440872],
       [  515.313791  ],
       [ 1395.77953819],
       [ 2067.57627122],
       [  734.62569466]])

In [9]:
XWtrain

array([[  9.11933786e-01,   1.03580980e-01,   1.40000000e+01,
          1.62000000e+02,   0.00000000e+00],
       [  4.70150369e-01,   3.33084588e-01,   6.00000000e+00,
          2.90000000e+01,   0.00000000e+00],
       [  2.91707554e-01,   1.68156301e+00,   1.70000000e+01,
          1.50000000e+02,   0.00000000e+00],
       [  4.93377631e-01,   6.54767645e-01,   4.00000000e+00,
          3.10000000e+01,   0.00000000e+00],
       [  7.44588697e-01,   3.46777075e-01,   3.00000000e+00,
          5.90000000e+01,   1.00000000e+00],
       [  9.01083926e-01,   4.07960379e-01,   1.70000000e+01,
          1.13000000e+02,   1.00000000e+00],
       [  7.66524185e-01,   4.84214071e-01,   1.00000000e+01,
          4.20000000e+01,   1.00000000e+00],
       [  7.23170737e-01,   1.76528205e+00,   1.40000000e+01,
          1.60000000e+01,   1.00000000e+00],
       [  6.06948241e-01,   7.74019678e-01,   1.90000000e+01,
          9.30000000e+01,   2.00000000e+00],
       [  4.77993761e-01,   5.8184882